version: '3.7'

services:

  frontend:
    image: frontend:v1
    container_name: frontend
    build:
      context: ./frontend
    environment:
      REACT_APP_API_URL: http://0.0.0.0:8080
    ports:
      - 80:3000
    restart: unless-stopped

  backend:
    image: backend:v1
    container_name: backend
    build:
      context: ./backend
    environment:
      PORT: 8080
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: abc-docker
      DB_USERNAME: root
      DB_PASSWORD: rootpw
      ENCRYPT_SECRET: thisIsAnExampleOfa32BytesSecret!
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.1.13
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports:
      - 27017:27017
    restart: unless-stopped
