version: '3.7'

services:

  frontend:
    image: node:12.14.1-alpine
    container_name: frontend
    working_dir: /usr/src/frontend
    command: "npm run start"
    environment:
      REACT_APP_API_URL: http://0.0.0.0:8080
    ports:
      - 80:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src/frontend
