version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1
  go:
    docker:
      - image: circleci/golang:1.13.4


jobs:
  setup_backend:
    executor: go
    steps:
      - checkout
      - run: cd backend && go mod vendor && go build
      - save_cache:
          key: setup_backend-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - backend
            - docker-compose.yaml

  test_backend:
    executor: go
    steps:
      - restore_cache:
          key: setup_backend-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd backend && go test ./...

  setup_frontend:
    executor: node
    steps:
      - checkout
      - run: cd frontend && npm i
      - save_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - frontend

  lint_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd frontend && npm run lint

  test_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd frontend && npm run test

  build_images:
    machine: true
    steps:
      - restore_cache:
          key: setup_backend-{{ .Environment.CIRCLE_SHA1 }}
      # - restore_cache:
      #     key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker-compose build
      - run: docker save -o ./backend.tar backend:v1
      - save_cache:
          key: docker-images-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - backend.tar

  bootstrap:
    executor: go
    steps:
      - restore_cache:
          key: docker-images-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: scp ./backend.tar remote-docker:/tmp/backend.tar
      - run: ssh remote-docker "pwd && ls -la && ls -la /tmp"
      # - run: docker load -i /tmp/backend.tar
      # - run: docker images


workflows:
  version: 2
  main:
    jobs:
      - setup_backend
      # - test_backend:
      #     requires:
      #       - setup_backend
      # - setup_frontend
      # - lint_frontend:
      #     requires:
      #       - setup_frontend
      # - test_frontend:
      #     requires:
      #       - setup_frontend
      - build_images:
          requires:
            - setup_backend
            # - lint_frontend
            # - test_frontend
      - bootstrap:
          requires:
            - build_images
