version: 2

jobs:
  lint_backend:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

  test_backend:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

  lint_frontend:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: cd frontend && npm i && npm run lint

  test_frontend:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: cd frontend && npm i && npm run test


workflows:
  version: 2
  main:
    jobs:
      # - lint_backend
      # - test_backend
      - lint_frontend
      - test_frontend
