version: 2

executors:
  my-executor:
    docker:
      - image: circleci/node:12.16.1

jobs:
  setup_frontend:
    executor: my-executor
    steps:
      - checkout
      - run: cd frontend && npm i
      - save_cache:
          key: setup_frontend-{{ arch }}-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend

  lint_frontend:
    executor: my-executor
    steps:
      - restore_cache:
          key: setup_frontend-{{ arch }}-{{ checksum "frontend/package-lock.json" }}
      - run: cd frontend && npm run lint

  test_frontend:
    executor: my-executor
    steps:
      - restore_cache:
          key: setup_frontend-{{ arch }}-{{ checksum "frontend/package-lock.json" }}
      - run: cd frontend && npm run test


workflows:
  version: 2
  main:
    jobs:
      - setup_frontend
      # - lint_frontend:
      #     requires:
      #       - setup_frontend
      # - test_frontend:
      #     requires:
      #       - setup_frontend
