version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1

jobs:
  setup_frontend:
    executor: node
    steps:
      - checkout
      - run: cd frontend && npm i
      - save_cache:
          key: setup_frontend-{{ arch }}-{{ .Branch }}
          paths:
            - frontend

  lint_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ arch }}{{ .Branch }}
      - run: pwd
      - run: npm run lint

  test_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ arch }}{{ .Branch }}
      - run: pwd
      - run: npm run test


workflows:
  version: 2
  main:
    jobs:
      - setup_frontend
      - lint_frontend:
          requires:
            - setup_frontend
      - test_frontend:
          requires:
            - setup_frontend
