version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1
  go:
    docker:
      - image: circleci/golang:1.13.4

jobs:
  setup_backend:
    executor: go
    steps:
      - checkout
      - run: cd backend && go get -u golang.org/x/lint/golint && cp /go/bin/golint . && go mod vendor
      - save_cache:
          key: setup_backend-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - backend

  lint_backend:
    executor: go
    steps:
      - restore_cache:
          key: setup_backend-{{ .Environment.CIRCLE_SHA1 }}
      - run: pwd && ls -la && ls -la backend
      - run: cd backend && ./golint .

  setup_frontend:
    executor: node
    steps:
      - checkout
      - run: cd frontend && npm i
      - save_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - frontend

  lint_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd frontend && npm run lint

  test_frontend:
    executor: node
    steps:
      - restore_cache:
          key: setup_frontend-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd frontend && npm run test


workflows:
  version: 2
  main:
    jobs:
      - setup_backend
      - lint_backend:
          requires:
            - setup_backend
      - setup_frontend
      - lint_frontend:
          requires:
            - setup_frontend
      - test_frontend:
          requires:
            - setup_frontend
